### ISSUE TITLE
Bucket Read node: Add spread, mode and stddev functions

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/node-red-contrib-thinger#21]
The spread, mode and stddev functions are very useful (especially spread). These functions are already available in Dashboard Widgets, but are not available in the Bucket Read node.

We really need the spread function in the Bucket Read node.

![nodered_imple](https://github.com/thinger-io/node-red-contrib-thinger/assets/22058152/e3e7e34b-9894-497d-ac88-b65359185114)

**Comment by georgevbsantiago** [comment]
Consider this issue about spread in implementation:
[The spread function does not count values in the defined time transition](https://github.com/thinger-io/thinger-server/issues/68)

**Comment by bautisflow** [comment]
Fixed and releases in version 1.5.0, as of 2023-11-16
