### ISSUE TITLE
The 'Bucket Reading' screen does not save the "Time Period" setting when 'months' is selected

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/node-red-contrib-thinger#30]
When trying to save the "Time Period" as "1" "months", the setting is reset to "1" "minutes".

https://github.com/thinger-io/node-red-contrib-thinger/assets/22058152/2ae516f4-74f0-483d-8593-c908e69d6a41

**Comment by georgevbsantiago** [comment]
the bug must be in the lines below that consider 'minutes' = 'm' and 'months' = 'm'

https://github.com/thinger-io/node-red-contrib-thinger/blob/062cfcaf26078205f6bb315ff5166eaea9e43774/nodes/bucket-read.html#L258

https://github.com/thinger-io/node-red-contrib-thinger/blob/062cfcaf26078205f6bb315ff5166eaea9e43774/nodes/bucket-read.html#L262

There is no corresponding month in the javascript file:
https://github.com/thinger-io/node-red-contrib-thinger/blob/062cfcaf26078205f6bb315ff5166eaea9e43774/nodes/bucket-read.js#L10-L28

**Comment by georgevbsantiago** [comment]
The documentation also needs to differentiate the reference value of 'minutes' and 'months'. Currently, they all point to the value 'm'

https://github.com/thinger-io/node-red-contrib-thinger/blob/062cfcaf26078205f6bb315ff5166eaea9e43774/nodes/bucket-read.html#L349

**Comment by bautisflow** [comment]
Thank you @georgevbsantiago , great contribution and analysis. If you ever feel like making a contribution to the repository let us know and we will help you.

This issue is already fixed for the oncoming release
