### ISSUE TITLE
[Asset Iterator Node] - Filter bucket and device by Project ID

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/node-red-contrib-thinger#32]
Allow filtering bucket and device by project id in the 'Asset Iterator' node

![image](https://github.com/thinger-io/node-red-contrib-thinger/assets/22058152/b87dff0c-280f-4fb6-8507-539353b497d3)

**Comment by bautisflow** [comment]
Hi @georgevbsantiago 

I believe this is regarding the asset iterator node. Let me know if I'm missing something. It will be added shortly in the asset iterator node

**Comment by georgevbsantiago** [comment]
Yes. I was the one who got confused. I changed the title and text of the issue.

**Comment by georgevbsantiago** [comment]
Filtering devices by project would also be very useful
