### ISSUE TITLE
Integration between NodeRed and the Form made with the HTML Widget

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/node-red-contrib-thinger#33]
Integration between NodeRed and the Form made with the HTML Widget.
Something similar to the “device_resource_stream” node, but it would be a “form_resource_stream”.
When the user fills in and clicks on the form button, it will generate an event in the NODERED node with a payload (JSON) containing the **name of the user who pressed the button** (it would be something equivalent to the device id), form data, ts, id of the dashboard, project id… With these payloads (JSON), it would be possible to develop more specific flows in NODERED using forms. (Currently it is possible to do something similar, using the device properties update node, but it is not possible to know which User (id or name) triggered the form)

**Comment by bautisflow** [comment]
Hi @georgevbsantiago, this extensions will never be able to handle this. I guess, you mean forms developed by using the HTML Widget on dashboards. This widgets don't have their own entity or API access and the development of something like this would be out of the scope of thinger.

One alternative to handle this is that the form widget on the dashboard modifies a device/group/type property, then in Node-RED with a server event node you may get the updated value.

I'll close the issue for now

**Comment by georgevbsantiago** [comment]
This implementation is very important to maximize the use of forms that can change property data and device resources. Furthermore, it would allow generating an event log for future audits or generating events in the NodeRed stream.

Furthermore, it allows you to send data to NodeRed, expanding its use in several possibilities (add, change or delete customer records (name, phone number, email).
Or even in situations where an operator can record information in a form already available in the HTML Widget.

Ultimately, the possibilities are endless.
And I don't see any other possibility, as it is not safe to expose NodeRed for public access.

**Comment by bautisflow** [comment]
At this moment this can't be handled directly by thinger. But the form may be passed to Node-RED by some other means, like making a direct HTTP request to a specific port listening on the Node-RED plugin.
Maybe in the future and with the continuous evolution of the platform we would be able to say otherwise.

**Comment by georgevbsantiago** [comment]
Ok. Thank you very much for working on the issues, @bautisflow
