### ISSUE TITLE
Include the Project, Description and name fields in payload the “device_stream” node

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/node-red-contrib-thinger#35]
As Node-Red works asynchronously it is not trivial to get this information from the “asset interactor” node and join with the information from the “device_stream” node.
And having these three information fields (“project”, “name” and “description”) in the device_stream node’s output would make it much easier to use along the flow, without requiring greater efforts to understand how the join node works and how it is possible to join the node information “device_stream” and “asset interactor”.
I did, but it took me a significant amount of time to understand how the join node works, especially given the asynchronous way that Node-RED works.
These three information fields (“project”, “name” and “description”) are important for us to use in the text of notification templates, for example.

![image](https://user-images.githubusercontent.com/22058152/216777632-c0d46ed1-0e0e-4e0e-9cd2-b6f6997eb35f.png)

**Comment by bautisflow** [comment]
Hi @georgevbsantiago, I understand  the usefulness of this, however I feel it should be handled by the server, as in this case, we are just returning the full event payload of a device_resource_stream. You can see its the same content as in the device inspector at the web console.

Using a join node is one way to handle this, but I think there is a better alternative. Usually this nodes only overwrite the `msg.payload` property, meaning that if you copy/move it to some other property before the message reaches the asset iterator node, on the returned message you will have all necessary information.

Node-RED is asyncronous in message passsing, meaning that one message may overtake another within the same flow, but for a same message, node actions will be handled sequentially. 

We can transfer the issue to the servers repository if its fine by you.

**Comment by georgevbsantiago** [comment]
Okay, @bautisflow 

Implementing the project field (at least) would be very useful for managing projects in the NodeRed flow.

Thanks

**Comment by georgevbsantiago** [comment]
> Usually this nodes only overwrite the `msg.payload` property, meaning that if you copy/move it to some other property before the message reaches the asset iterator node, on the returned message you will have all necessary information.

It is not possible to do this with the asset interactor node. It does not preserve the other fields of the msg.
It sends a new message only with the result of the asset interactor node. Therefore, it is necessary to do the join to combine the initial message with the result of the asset interactor (ex: field project id).

**Comment by georgevbsantiago** [comment]
If the asset interector node preserves the msg input data, then this problem can be circumvented.  If possible, we can place the device_stream message data in another msg key.  Ex: msg.device_stream = msg;  When the interector asset node pushes the output data, the input data would be preserved. 
Placing an option on the configuration screen "Preserve input data?"  and the user would mark.  This would avoid bugs.  The default may be "NO" to avoid bugs.  What do you think?

**Comment by bautisflow** [comment]
It is being preserved, you may need to move the payload of the msg before it enters the asset iterator node.

![screen 20231129-212257](https://github.com/thinger-io/node-red-contrib-thinger/assets/24596269/756f8699-aedd-4aaf-9228-114215bbe551)

**Comment by georgevbsantiago** [comment]
Hmm... I think our "debug" node was only showing the payload, and not the entire object.
Thank you very much, @bautisflow  for the message.
You can close this issue.
Thank
