### ISSUE TITLE
Add Node for Export Bucket

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/node-red-contrib-thinger#36]
It would be interesting to have a node available to export data from the bucket, returning the URL of the file (CSV, JSON, ARFF) in the payload or the file itself (binary file).

Some of our customers want access to sensor data recorded in the bucket, in CSV file format.

-  Preferably, the "Specify a custom data range for export the data" must obey the UTC selected by the user. In our case, UTC -03:00
- An option to set the file name, before saving it to the storage system.
- Opções para deletar o arquivo

This implementation would facilitate this flow, which we are currently developing with the function node.

![image](https://github.com/thinger-io/node-red-contrib-thinger/assets/22058152/223a5895-fb2a-4bcb-841d-e3b2ba643035)

**Comment by georgevbsantiago** [comment]
The purpose of this implementation is to be able to send the URL link or binary file to clients or applications, via email or upload to Dropbox, Google Drive, Onedrive...

**Comment by bautisflow** [comment]
coming soon :)

This node will launch and synchronously return the event of `bucket_export_complete`, which contains the resulting URL of the file. An additional option is provided to return the file contents instead alongside the url.

Options for setting a custom filename or deleting the files can not be provided as this features are missing the thinger server backend.

**Comment by bautisflow** [comment]
Released as of version 1.8.0
