### ISSUE TITLE
[Asset Iterator Node] - The devices combobox does not work

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/node-red-contrib-thinger#40]
The devices combobox does not work.
The others (asset type, group, project) work
![image](https://github.com/thinger-io/node-red-contrib-thinger/assets/22058152/364677b3-5b17-4556-ad99-4c63d89c383c)
![image](https://github.com/thinger-io/node-red-contrib-thinger/assets/22058152/e59e989a-cb93-4061-85b1-2fa63dae438a)
![image](https://github.com/thinger-io/node-red-contrib-thinger/assets/22058152/935fd072-0f58-4c5c-a535-396bf5cd4737)

**Comment by georgevbsantiago** [comment]
Does this line also need to be changed?
for:
msg.payload.asset_filter = queryParameters.get(" **name** ");
https://github.com/thinger-io/node-red-contrib-thinger/blob/ca4f7dfb5eb7f66fc03eb4a76dc6a195361cb4bb/nodes/asset-iterator.js#L115

**Comment by bautisflow** [comment]
Hi @georgevbsantiago 
Yes, that line will be changed. Will add it to the next version of the extension.
Regarding the combobox for devices, this behavior is expected, as it is more a filter than an enforce over the full id of the asset. For asset type, group and project. The full id needs to be set, that why the select is there.

**Comment by georgevbsantiago** [comment]
> Does this line also need to be changed? for: msg.payload.asset_filter = queryParameters.get(" **name** ");
> 
> https://github.com/thinger-io/node-red-contrib-thinger/blob/ca4f7dfb5eb7f66fc03eb4a76dc6a195361cb4bb/nodes/asset-iterator.js#L115

Reminder: Include this fix in the next version 1.6.2
https://github.com/thinger-io/node-red-contrib-thinger/milestone/4
