### ISSUE TITLE
Urgent! - [Asset Iterator Node] - Device and Bucket id field is ignored

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/node-red-contrib-thinger#41]
The iterator does not consider the information in the device field and, therefore, returns all devices.

This bug must be related to this issue: https://github.com/thinger-io/node-red-contrib-thinger/issues/40

![image](https://github.com/thinger-io/node-red-contrib-thinger/assets/22058152/c3d3cd44-b247-4a13-a2c9-23c605be6432)

**Comment by georgevbsantiago** [comment]
We are trying to find the bug, as we need the asset interactor node to get the project number. Without the project number, our NodeRed flow BREAKS!
Is this syntax correct?

https://github.com/thinger-io/node-red-contrib-thinger/blob/22823ceb9c844e851c5eb464901cb1902940a7a6/nodes/asset-iterator.js#L74
__________________________________________________________________________________

Is this syntax correct?  Before was: **name**=${filter}

Before:
`name=${filter}&count=${count}`
After:
`count=${count}&${queryParametersString}`
`queryParametersString `Won't return filter={filter}?

https://github.com/thinger-io/node-red-contrib-thinger/blob/22823ceb9c844e851c5eb464901cb1902940a7a6/nodes/asset-iterator.js#L90

**Comment by georgevbsantiago** [comment]
The same problem occurs when trying to assign the bucket id. It is not considered, even when filling out the screen or defining it in the message.

![image](https://github.com/thinger-io/node-red-contrib-thinger/assets/22058152/ce67447b-a74a-4590-8251-19b0de23e10a)

**Comment by georgevbsantiago** [comment]
Our suspicion is that the bug is in this change:

before the key name was "**name**"
`name=${filter}&count=${count}`
After:
`count=${count}&${queryParametersString}`
queryParametersString Won't return filter={filter}?

https://github.com/thinger-io/node-red-contrib-thinger/blob/22823ceb9c844e851c5eb464901cb1902940a7a6/nodes/asset-iterator.js#L90

**Comment by georgevbsantiago** [comment]
Hello, @bautisflow 
Does this line also need to be changed?
for:
msg.payload.asset_filter = queryParameters.get(" **name** ");
https://github.com/thinger-io/node-red-contrib-thinger/blob/ca4f7dfb5eb7f66fc03eb4a76dc6a195361cb4bb/nodes/asset-iterator.js#L115

**Comment by bautisflow** [comment]
Yeah, missed it. Will add it to the next version of the extension.
